name: CI/CD Pipeline TP Final

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: 1. Configurer l'infrastructure (Partie 1)
        run: |
          # On rend les scripts exécutables et on génère l'inventaire
          chmod +x *.sh
          ./generate_inventory.sh

      - name: Connexion au Docker Hub
        
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 2. Builder et Pousser l'image Docker (Partie 2)
        run: |
          # Build de l'image optimisée 
          sudo docker build -t errwwaann/lacet-api:latest .
          # Push vers Docker Hub 
          sudo docker push errwwaann/lacet-api:latest

      - name: 3. Déployer sur K3s (Partie 3)
        run: |
          # Application des manifests Kubernetes 
          # L'utilisation de 'apply' garantit l'idempotence demandée 
          sudo kubectl apply -f ./k8s/api.yaml
          sudo kubectl apply -f ./k8s/mysql.yaml
